variable "environment" {
  description = "Deployment stage name (staging, prod)."
  type        = string
}

variable "extra_values" {
  description = "Additional key/value pairs merged into the bowline/<env>/app bundle, for third-party credentials that are not generated by Terraform. Keys should be environment variable names."
  type        = map(string)
  default     = {}
  sensitive   = true
}

variable "secret_recovery_window_days" {
  description = "Days before a deleted Secrets Manager secret is purged (0 for immediate, 7 to 30 otherwise)."
  type        = number
  default     = 7
}

variable "kms_key_id" {
  description = "KMS key for the secrets. Null uses the AWS managed key."
  type        = string
  default     = null
}

variable "tags" {
  description = "Additional tags applied to every resource in this module."
  type        = map(string)
  default     = {}
}
